server:
  port: 8080

security:
  jwt:
    secret: "inventra-super-secret-key-change-this-in-prod-123456"
    expiration-minutes: 60

spring:
  application:
    name: inventra-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/inventra
    username: inventra
    password: inventra

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
